services:
  nexus-builder:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        - APP_NAME=${APP_NAME:-nexus-builder}
        - RUST_DIR=${RUST_DIR:-rust}
        - TZ=${TZ:-UTC}
    env_file:
      - ../.env
    container_name: ${APP_NAME:-nexus-builder}
    ports:
      - "${APP_PORT:-8000}:8000"
    volumes:
      - ../:/app/
      - ./fish_history:/root/.local/share/fish
      - ./fish_config:/root/.config/fish
